apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-agent
  template:
    metadata:
      labels:
        app: ai-agent
    spec:
      containers:
        - name: ai-agent
          image: ghcr.io/melissalhb/lab_mcp_ai_agent_springboot:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          # --- LES VARIABLES MANQUANTES SONT ICI ---
          env:
            - name: ANTHROPIC_API_KEY
              value: "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" 
            - name: GITHUB_OWNER
              value: "melissalhb" 
            - name: GITHUB_REPO
              value: "lab_mcp_ai_agent_springboot"
---
apiVersion: v1
kind: Service
metadata:
  name: ai-agent-service
spec:
  type: NodePort 
  selector:
    app: ai-agent
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080 